### ISSUE TITLE
VCR emits error messages containing broken doc links, stranding the user

### ISSUE THREAD

**Issue by jm3** [vcr/vcr#694] opened 2018-02-09 18:42 UTC
vcr (4.0.0) / ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]

[1] https://www.relishapp.com/vcr/vcr/v/4-0-0/docs/configuration/debug-logging
[2] https://www.relishapp.com/vcr/vcr/v/4-0-0/docs/record-modes/new-episodes
[3] https://www.relishapp.com/vcr/vcr/v/4-0-0/docs/configuration/ignore-request
[4] https://www.relishapp.com/vcr/vcr/v/4-0-0/docs/record-modes/once
[5] https://www.relishapp.com/vcr/vcr/v/4-0-0/docs/request-matching

RelishApp dot com returns a 500 error for the above links with the Rails default error message:

> We're sorry, but something went wrong.
> We've been notified about this issue and we'll take a look at it shortly.

**Comment by krainboltgreene** [comment] 2018-02-11 01:31
I have no control over RelishApp :(

**Comment by jm3** [comment] 2018-02-11 18:15
Ha, I don't either. I don't know what relishapp is. I just know that when I run tests, VCR prints a bunch of URLs saying something like, "to learn more about fixing this problem, click on these clicks", and none of the links work, which erodes my confidence in VCR as an up-to-date, user-friendly too.

So I wonder if we could maybe replace these with doc link(s) that's more likely to remain up to date — maybe to the docs on github or rubydoc, or a link that's not version specific?

**Comment by eiapopeia** [comment] 2019-05-14 11:18
#712 (which seems like a duplicate of this ticket) says that relishapp is closing down.

**Comment by krainboltgreene** [comment] 2019-05-31 15:37
It's definitely dead.

**Closed by krainboltgreene** 2019-05-31 15:37 UTC
Labels: help wanted
