### ISSUE TITLE
Cucumber scenario outlines use incorrect cassette

### ISSUE THREAD

**Issue by AgentAntelope** [vcr/vcr#517] opened 2015-11-03 16:49 UTC
We're experiencing some odd behaviour since upgrading to `v3.0.0`, specifically we've tracked this down to https://github.com/vcr/vcr/commit/c16e8cc1b7066fc4e46c0c014ccd97509a038e87#diff-1c6bdcf6421dae582fbc386e7f988f5cR364.

We're using cucumber on a webrick server, which maintains its own thread for running the application. This means that in scenario outlines, the webrick thread duplicates the context (and thus, the cassette) of the main thread during the first scenario variant, but as the webrick thread isn't refreshed between tests this cassette is still in use in the subsequent scenario variants, even though the main thread's context has moved on.

The code that solved the issue for us changes `#get_context` like so: 

```@ruby
  def get_context(thread_key, fiber_key = nil)
    context = @context[fiber_key] if fiber_key
    context ||= @context[thread_key]
    if context
      context
    else
      @context[MainThread]
    end
  end
```

Essentially, we rely on the main thread to maintain our context for us, rather than duplicating that context to threads that may remain in use beyond the context of a specific scenario variant. However, I don't know whether this meets the requirements for thread safety and JRuby compatibility. I'd appreciate some feedback, and am happy to raise a PR if this solves the issue.

Thanks :)

**Comment by bmulholland** [comment] 2015-11-04 19:51
+1, I'm getting the same thing. In particular, what I'm seeing is that VCR isn't finding the recorded cassette. In the error, it tells me that it is looking in the cassette file for a previous, unrelated, cucumber test. I will downgrade cucumber for now.

**Comment by djberg96** [comment] 2015-11-04 20:36
Paging @mrbrdo - what do you think?

**Comment by mrbrdo** [comment] 2015-11-05 06:40
Good description, it makes sense.
I think there were a few reasons I duplicated the context instead of using the main thread's one. One is that it avoids locks so it's more performant, and I think it was also necessary because of `around_http_request`, since it will insert/eject cassettes for each request during the same test. Solving this in a better way might actually be much easier if https://github.com/vcr/vcr/issues/461 is done, as `around_http_request` is the source of much of the complexity here.

For this particular case: I am wondering if using your webrick's thread as the `MainThread` would solve the problem for you? You could try just overriding the constant to try this out, like:
```ruby
module ::VCR
  MainThread = some_thread
  initialize_ivars # important to call this as well
end
```
However this should be done before doing any vcr **stuff**. If that would solve the problem we could change the constant into a class attr_accessor with a writer to reinitialize the ivars. As a quick fix. I think it might work as usually you'd always have a main thread in tests that may then be spawning shorter-lived threads. The idea is that the cassettes in the main thread are basically not being inserted/ejected while other "sub"-threads are working with vcr.

Just to comment on your `get_context` patch, I don't think it would be thread safe on JRuby (or any other interpreter without a GIL/GVL).

PS: I'm a bit short on time for the next week but I'll try to help as I can.

**Comment by krainboltgreene** [comment] 2015-11-06 19:10
I appreciate your help @mrbrdo!

**Comment by mrbrdo** [comment] 2015-11-10 15:50
@AgentAntelope @bmulholland have you guys been able to try out my suggestions?

**Comment by AgentAntelope** [comment] 2015-11-10 15:52
I haven't; it appears that the webrick thread doesn't necessarily live till the end of the tests, it just /sometimes/ does. Which makes a coherent source for that thread difficult.

**Comment by mrbrdo** [comment] 2015-11-10 15:58
Would it be possible to provide a simple example of this setup so I can test it?

**Comment by AgentAntelope** [comment] 2015-11-10 16:24
I haven't been able to find a nice subset of our codebase that reproduces this issue, I'm afraid. Sorry I can't be more help :(

**Comment by bmulholland** [comment] 2015-11-11 01:03
@mrbrdo Sorry, I'm not very familiar with the internals of what's happening here. Where is `webrick_thread` coming from? It's not set in any context I can find. Seems that capybara is automatically creating the webrick server for me, so I don't touch it at all.

**Comment by drogar** [comment] 2015-11-16 22:09
I ran into this (or a similar issue) today using rspec.  Tests were marked as `js: true`, which means they were using webkit as the test runner. I will see if I can create an isolated test example later this week.  (we've downgraded to VCR 2.9.3 in the meantime)

**Comment by mrbrdo** [comment] 2015-11-16 23:54
Thanks, an example app will help a bunch!

**Comment by drogar** [comment] 2015-12-03 19:37
Here you go. (It took a while to trim out everything else).
[vcr-bug-517-demo-app.zip](https://github.com/vcr/vcr/files/51241/vcr-bug-517-demo-app.zip)

**Comment by drogar** [comment] 2015-12-04 04:30
Demo app for your use:  
[vcr-bug-517-demo-app.zip](https://github.com/vcr/vcr/files/51643/vcr-bug-517-demo-app.zip)

**Comment by mrbrdo** [comment] 2015-12-04 04:45
Thanks, at the moment I am really short on time but I'll try to look into this in about a week.

**Comment by mrbrdo** [comment] 2015-12-05 15:34
Luckily I had some time today.
Can you try this: https://github.com/mrbrdo/vcr/tree/fix_issue_517
`gem 'vcr', github: 'mrbrdo/vcr', branch: 'fix_issue_517'`
@drogar your tests seem to be passing for me now
@AgentAntelope @bmulholland could you try this as well?

**Comment by drogar** [comment] 2015-12-05 19:18
Awesome. Fixed in the main app where we initially had the problem. Many thanks @mrbrdo !

**Comment by AgentAntelope** [comment] 2015-12-06 15:23
Likewise, this fixes the issue for me (I also re-upgraded to `3.0.0` to ensure the only differences were between `3.0.0` and this patch, and not in our code).

Thanks for looking into this :+1:

**Comment by kyamaguchi** [comment] 2015-12-07 02:12
I had  the similar issue last week. (incorrect cassette)
Random failing spec have disappeared with `gem 'vcr', github: 'mrbrdo/vcr', branch: 'fix_issue_517'`.
Thanks @mrbrdo .

**Comment by bmulholland** [comment] 2015-12-07 20:04
@mrbrdo I can confirm that the fix branch fixed my tests as well! Thank you!

**Closed** 2015-12-11 01:51 UTC
Labels: bug
