### ISSUE TITLE
Links to the docs in the error message are not working

### ISSUE THREAD

**Issue by adamniedzielski** [vcr/vcr#525] opened 2015-11-25 07:49 UTC
```
     Failure/Error: expect { service.call("google.com") }.to change { Company.count }.by(1)
     VCR::Errors::UnhandledHTTPRequestError:

       [1] https://www.relishapp.com/vcr/vcr/v/3-0-0/docs/configuration/debug-logging
       [2] https://www.relishapp.com/vcr/vcr/v/3-0-0/docs/getting-started
       [3] https://www.relishapp.com/vcr/vcr/v/3-0-0/docs/configuration/allow-http-connections-when-no-cassette
       [4] https://www.relishapp.com/vcr/vcr/v/3-0-0/docs/configuration/ignore-request
       ================================================================================
```

The links (for example https://www.relishapp.com/vcr/vcr/v/3-0-0/docs/configuration/debug-logging) are not working. They render "We're sorry, but something went wrong." page. However, when I change the version number in the URL to 2.9.3 they do work.

**Comment by mcfiredrill** [comment] 2015-11-26 08:37
@krainboltgreene @myronmarston I found the relish rake task. I don't believe I have credentials tho, unless relish is linked to github?

**Comment by krainboltgreene** [comment] 2015-11-26 09:08
Yeah, I'll have to do it. I'll do it tomorrow. BTW, @mcfiredrill, try not to message myron, he's usually not going to be available.

**Comment by galori** [comment] 2015-11-29 08:20
@krainboltgreene @mcfiredrill looks like relishapp.com doesn't have docs for vcr 3.0.  Is that something @krainboltgreene can handle?

Alternatively (or temporarily?) the code could be changed to link to a non-versioned URL.

https://github.com/vcr/vcr/blob/cc57fc4c6da01c37ecb5700040a5eeda5633e12a/lib/vcr/errors.rb

Links to:

https://www.relishapp.com/vcr/vcr/v/3-0-0/docs/configuration/debug-logging

But could instead link to:

https://www.relishapp.com/vcr/vcr/docs/configuration/debug-logging

**Comment by jm3** [comment] 2017-12-13 03:45
Hi, I stumbled upon this after encountering the same problem today. Any way there can be a stop-gap or some other small, partial fix?

**Comment by eiapopeia** [comment] 2019-05-14 11:26
Duplicate of #698 
Duplicate of #594

**Comment by krainboltgreene** [comment] 2019-05-31 15:35
Apparently relish is just dead now. I just got an email from the team and they've moved on to something called Jam. Annoying that it took so long to be told this, but basically no more changes to the relish documentation.

Not sure what I'll do.

**Closed by krainboltgreene** 2019-05-31 15:35 UTC

**Comment by jm3** [comment] 2019-05-31 15:53
Can you explain to us / remind us what relish is / was? I’m not sure the non-core developers understand why this other service is causing vcr to emit broken links. I thought relish was like hosted Redis or something?

**Comment by krainboltgreene** [comment] 2019-05-31 16:03
Not at all. It's a way to host cucumber files as documentation.
